# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            响马读书
tagline:          'python, emacs'
url:              http://greenhoodreading.github.io

author:
  name:           'GreenHoodReading'
  url:            http://greenhoodreading.github.io

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:		  https://github.com/greenhoodreading/greenhoodreading.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
